// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var Modifier = {};

var Color = {};

var BgColor = {};

var ColorModel = {};

var BgColorModel = {};

function applyU(t, str) {
  return t(str);
}

function applyManyU(t, strArray) {
  return t(strArray);
}

function apply(t, str) {
  return t(str);
}

function applyMany(t, strArray) {
  return t(strArray);
}

var Impl = {
  Modifier: Modifier,
  Color: Color,
  BgColor: BgColor,
  ColorModel: ColorModel,
  BgColorModel: BgColorModel,
  applyU: applyU,
  applyManyU: applyManyU,
  apply: apply,
  applyMany: applyMany
};

exports.Impl = Impl;
exports.Modifier = Modifier;
exports.Color = Color;
exports.BgColor = BgColor;
exports.ColorModel = ColorModel;
exports.BgColorModel = BgColorModel;
exports.applyU = applyU;
exports.applyManyU = applyManyU;
exports.apply = apply;
exports.applyMany = applyMany;
/* No side effect */
